# Numpy Case Study2

***

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmetic operations metioned in below "print" statements

In [2]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9).reshape(3,3))
mat2 = np.array(ri(1,10,9).reshape(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n",mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", +(3*mat1-2*mat2))


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",mat1**0.5)


1st Matrix of random single-digit numbers
----------------------------------------
 [[2 2 2]
 [3 1 9]
 [8 7 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 6 2]
 [8 1 8]
 [5 3 9]]

Addition
------------------
 [[ 8  8  4]
 [11  2 17]
 [13 10 18]]

Multiplication
------------------
 [[12 12  4]
 [24  1 72]
 [40 21 81]]

Division
------------------
 [[0.33333333 0.33333333 1.        ]
 [0.375      1.         1.125     ]
 [1.6        2.33333333 1.        ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-6 -6  2]
 [-7  1 11]
 [14 15  9]]

Addition of a scalar (100)
-------------------------
 [[102 102 102]
 [103 101 109]
 [108 107 109]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  8   8   8]
 [ 27   1 729]
 [512 343 729]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[1.41421356 1.41421356 1.41421356]
 [1.73205081 1.         3.        ]
 [2.82

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [3]:
from numpy.random import randint as ri
mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.product(mat1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.product(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = ri(1,99,9).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[6 4 5]
 [2 1 4]
 [4 1 6]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 5 6]
 [9 9 5]
 [9 3 5]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 33

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [12  6 15]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [15  7 11]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 23040

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [405 135 150]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 3.6666666666666665

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 1.825741

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [4]:
mat=ri(1,20,10)
mat1 = ri(1,10,9).reshape(3,3)
print("\n3*3 Matrix \n","-"*25,"\n",mat1)
mat=mat1.reshape(9,1)
print("\nModified Matrix of shape 9*1\n","-"*25,"\n",mat)


3*3 Matrix 
 ------------------------- 
 [[3 6 5]
 [9 9 1]
 [2 5 6]]

Modified Matrix of shape 9*1
 ------------------------- 
 [[3]
 [6]
 [5]
 [9]
 [9]
 [1]
 [2]
 [5]
 [6]]


### 4.Sort

In [5]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A,kind='mergesort'))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [45 92 75 91 51 54 34 62 22 47]

Here is the sorted vector
 -------------------------------------------------- 
 [22 34 45 47 51 54 62 75 91 92]


In [6]:
M = ri(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0,kind='mergesort',))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[90 75 86 23 88]
 [69 37 43 12  8]
 [ 5 65 19 54 60]
 [30 91 76 41 77]
 [53 38  1 45 24]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[23 75 86 88 90]
 [ 8 12 37 43 69]
 [ 5 19 54 60 65]
 [30 41 76 77 91]
 [ 1 24 38 45 53]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 5 37  1 12  8]
 [30 38 19 23 24]
 [53 65 43 41 60]
 [69 75 76 45 77]
 [90 91 86 54 88]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [7]:
# Fill the following ***** with appropriate solution.
a=ri(1,100,10).reshape(5,2)
b=ri(1,50,10).reshape(2,5)
c=ri(25,50,10).reshape(5,2)

print("\na\n",'-'*50,"\n",a)

print("\nb\n",'-'*50,"\n",b)

print("\nc\n",'-'*50,"\n",c)

print("Max of a:",a.max())
print("Max of b:",b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

a=ri(1,20,10).reshape(5,2)
b=ri(1,100,10).reshape(5,2)
c=ri(1,200,10).reshape(5,2)

print("\na\n",'-'*50,"\n",a)

print("\nb\n",'-'*50,"\n",b)

print("\nc\n",'-'*50,"\n",c)

print("Max of a:",a.max())
print("Max of b:",b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())




a
 -------------------------------------------------- 
 [[97 86]
 [18 10]
 [ 4 67]
 [90  6]
 [70  4]]

b
 -------------------------------------------------- 
 [[ 8 38  9 30 42]
 [ 5 25  3  8 37]]

c
 -------------------------------------------------- 
 [[32 46]
 [48 29]
 [42 35]
 [34 48]
 [49 31]]
Max of a: 97
Max of b: 42
Max of a location: 0
Max of b location: 4
Max of c location: 8

a
 -------------------------------------------------- 
 [[15 17]
 [19 15]
 [ 6  5]
 [ 4 12]
 [14 11]]

b
 -------------------------------------------------- 
 [[57 89]
 [68 30]
 [26  7]
 [64 77]
 [65 76]]

c
 -------------------------------------------------- 
 [[182  36]
 [ 82  88]
 [126  39]
 [100  87]
 [ 25 116]]
Max of a: 19
Max of b: 89
Max of a location: 2
Max of b location: 1
Max of c location: 0


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [8]:
mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n",np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[9 7 1]
 [2 1 4]
 [1 9 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 2 5]
 [7 5 3]
 [5 6 5]]

Sq-root of 1st matrix using np
------------------
 [[3.         2.64575131 1.        ]
 [1.41421356 1.         2.        ]
 [1.         3.         1.41421356]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 1.09663316e+03 2.71828183e+00]
 [7.38905610e+00 2.71828183e+00 5.45981500e+01]
 [2.71828183e+00 8.10308393e+03 7.38905610e+00]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.84509804 0.        ]
 [0.30103    0.         0.60205999]
 [0.         0.95424251 0.30103   ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[4 1 1]
 [2 1 1]
 [1 3 2]]


### 7.Generating matrices from distributions

In [9]:
print("Random number generation (from Uniform distribution)")
print(np.random.uniform(0,1,6).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.normal(0, 1, 6).reshape(2,3))
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)


Random number generation (from Uniform distribution)
[[0.6435129  0.0141514  0.15771237]
 [0.53854395 0.60591671 0.6692417 ]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.88386645 -0.12242978 -1.64800994]
 [-0.94735523  1.01113034  1.44567162]]
Random integer vector: [20 77 58 47 10  8 22 53 92 64]

Random integer matrix
[ 7  9 35 36 48 76 96 51 63 28]


In [10]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("\nNumbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("\nRandom integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.7179444  0.46045301 0.96236796]
 [0.60154003 0.21431962 0.03789327]]

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.25591927  0.69217262 -1.51023883]
 [ 1.3578843   0.28967137 -0.70102506]
 [-0.33001218  0.17878466  0.59816539]
 [ 0.51413542  0.14285419 -1.76361922]]

Random integer vector: [11 10 29 97 51 20 49 57 72 73]

Random integer matrix
[[39 16 69  4]
 [28 36 33 36]
 [22 64 81 90]
 [38 78 23 93]]

20 samples drawn from a dice throw: [2 4 5 6 5 2 1 1 5 2 3 4 1 4 5 2 1 2 1 1]


### 8.Find the nearest value from a given number in an array using NumPy.

In [11]:
import numpy as np
x = np.random.uniform(1, 12, 5)
print("Array of elements : ",x)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

Array of elements :  [ 2.48338231 11.02144672  5.93604664  5.20318476  6.46186375]
5.203184760722424


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [12]:
A =np.array([[0,0,0],[0,1,2],[0,2,4]])

print(A) 


[[0 0 0]
 [0 1 2]
 [0 2 4]]


***